name: CombatLog
main: com.github.neapovil.combatlog.CombatLog
version: 1.0.0
api-version: 1.13
author: Neapovil
website: https://github.com/neapovil/combatlog
permissions:
  combatlog.command:
    default: op
